# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myGui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from PyQt5.QtCore import QDir
from PyQt5.QtGui import QImage


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(628, 381)
        self.filePath = ''
        self.previewPath = ''
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 281, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.TopLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.TopLayout.setContentsMargins(20, 0, 20, 0)
        self.TopLayout.setObjectName("TopLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.TopLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setEnabled(False)
        self.TopLayout.addWidget(self.comboBox)
        self.TopLayout.setStretch(1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 60, 621, 221))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(10, 0, 10, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.OptionsBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget_2)
        self.OptionsBox.setObjectName("OptionsBox")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.OptionsBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 331, 181))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setHorizontalSpacing(7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.label_18.setVisible(False)
        self.gridLayout_2.addWidget(self.label_18, 4, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.label_13.setVisible(False)
        self.gridLayout_2.addWidget(self.label_13, 3, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.label_17.setVisible(False)
        self.gridLayout_2.addWidget(self.label_17, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.label_12.setVisible(False)
        self.gridLayout_2.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.label_15.setVisible(False)
        self.gridLayout_2.addWidget(self.label_15, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setVisible(False)
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setVisible(False)
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setVisible(False)
        self.gridLayout_2.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_4.setVisible(False)
        self.gridLayout_2.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_5.setVisible(False)
        self.gridLayout_2.addWidget(self.lineEdit_5, 4, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 2)
        self.horizontalLayout.addWidget(self.OptionsBox)
        self.PropertiesBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget_2)
        self.PropertiesBox.setObjectName("PropertiesBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.PropertiesBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 221, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayoutProp = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayoutProp.setContentsMargins(5, 5, 5, 5)
        self.gridLayoutProp.setObjectName("gridLayoutProp")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayoutProp.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayoutProp.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayoutProp.addWidget(self.label_5, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayoutProp.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayoutProp.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayoutProp.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayoutProp.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayoutProp.addWidget(self.label_9, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayoutProp.addWidget(self.label_10, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayoutProp.addWidget(self.label_11, 4, 1, 1, 1)
        self.gridLayoutProp.setRowStretch(4, 1)
        self.horizontalLayout.addWidget(self.PropertiesBox)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 279, 621, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_2.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.previewBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.previewBtn.setObjectName("previewBtn")
        self.previewBtn.setEnabled(False)
        self.horizontalLayout_2.addWidget(self.previewBtn)
        self.submitBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.submitBtn.setObjectName("submitBtn")
        self.submitBtn.setEnabled(False)
        self.horizontalLayout_2.addWidget(self.submitBtn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 628, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(shortcut="Ctrl+O",triggered=self.open)
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())
        self.label.setBuddy(self.comboBox)
        self.label_18.setBuddy(self.lineEdit_5)
        self.label_13.setBuddy(self.lineEdit_4)
        self.label_17.setBuddy(self.lineEdit_3)
        self.label_12.setBuddy(self.lineEdit)
        self.label_15.setBuddy(self.lineEdit_2)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBox, self.previewBtn)
        MainWindow.setTabOrder(self.previewBtn, self.submitBtn)
        MainWindow.setTabOrder(self.submitBtn, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        MainWindow.setTabOrder(self.lineEdit_4, self.lineEdit_5)

    def open(self):
        fileName, _ = QFileDialog.getOpenFileName(self, "Open File",
                QDir.currentPath())
        self.filePath = fileName
        self.previewPath = fileName
        print(fileName)
        if fileName:
            image = QImage(fileName)
            if image.isNull():
                QMessageBox.information(self, "Image Viewer",
                        "Cannot load %s." % fileName)
                return

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Operation : "))
        self.comboBox.setItemText(0, _translate("MainWindow", "Resize"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Scale"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Rotate"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Face Detection"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Blur Image"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Edge lines"))
        self.OptionsBox.setTitle(_translate("MainWindow", "Options "))
        self.label_18.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.label_17.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.label_15.setText(_translate("MainWindow", "TextLabel"))
        self.PropertiesBox.setTitle(_translate("MainWindow", "Properties "))
        self.label_2.setText(_translate("MainWindow", " Height : "))
        self.label_7.setText(_translate("MainWindow", " Type : "))
        self.label_5.setText(_translate("MainWindow", " - "))
        self.label_4.setText(_translate("MainWindow", " Width : "))
        self.label_3.setText(_translate("MainWindow", " - "))
        self.label_6.setText(_translate("MainWindow", " Size : "))
        self.label_8.setText(_translate("MainWindow", " Location : "))
        self.label_9.setText(_translate("MainWindow", " - "))
        self.label_10.setText(_translate("MainWindow", " - "))
        self.label_11.setText(_translate("MainWindow", " - "))
        self.previewBtn.setText(_translate("MainWindow", "Preview"))
        self.submitBtn.setText(_translate("MainWindow", "Save"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
